- data/themes/asciidoctor-theme.yml
- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
Also added the possibility to specify the background color for even table rows.
> Fixed #104, table header background color

- README.adoc
- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
- support setting page size via pdf-page-size attribute
- add support for units in page size
- validate named page size
- document page size options in default theme file
> resolves #65 support setting page size via attribute

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/coderay_encoder.rb
- add method for extracting conums from source string
- add method for restoring conums to source fragments
- add method for resolve conum glyph
- minor cleanups to CodeRay encoder
> resolves #31 process callouts in source blocks when using CodeRay

- lib/asciidoctor-pdf/converter.rb
It's not pretty yet, but I think this resolves images in a way consistent with the html5 backend when data-uri is set.
> resolves #87 properly resolve image target as system path

- lib/asciidoctor-pdf/converter.rb
- eagerly check if image is readable and warn if not
- don't crash if image cannot be read from URI
- only load open-uri/cached if ::OpenURI::Cache is not defined
- clarify documentation on resolve_image_path method
- cleanup warning messages
- minor code cleanups
> resolves #148 show warning when image cannot be read

- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- don't create new page if cursor is at page top
> resolves #150 keep together shouldn't create blank pages

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/formatted_text/transform.rb
- introduce add_dest_for_block for adding xref targets (i.e, destinations)
- call add_dest_for_block in each block handler
- add support in parser for <a name> to set inline destinations
- handle render_behind callback to add inline destinations
- enable inline ref and bibref targets
> resolves #110 fix xrefs to non-section content

- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
- render table footer row
- allow footer row text properties to be customized
> resolves #123 render table footer row

- lib/asciidoctor-pdf/converter.rb
- add link annotation overlay on image if image has link attribute
- only read SVG data once (outside of keep_together block)
> resolves #51 add link annotation to image with link attribute

- lib/asciidoctor-pdf/theme_loader.rb
before passing theme data to YAML.load:
- remove leading # from hex colors
- quote hex colors
> resolves #158 preprocess theme data to properly support hex colors

- data/themes/asciidoctor-theme.yml
- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
* name per-level heading theme keys consistently
* add support for font family and style per heading level
> resolves #157 name per-level heading theme keys consistently

- lib/asciidoctor-pdf/converter.rb
- add support for inline icon macro
- allow font set to be changed globally (icon-set=<icon-set> attribute)
- allow font set to be changed per icon (set=<icon-set> attribute or append @<icon-set> to target)
> resolves #97 add support for inline icon macro

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- add support for line_style to stroke_horizontal_rule method
- allow border style to be set for running header/footer and thematic break
- document new keys
- lowercase all color values and prefix with # in theming guide
> resolves #196 add support for border style

- lib/asciidoctor-pdf/core_ext.rb
- lib/asciidoctor-pdf/core_ext/ostruct.rb
> resolves #81 add missing methods on ostruct for Rubinius

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/theme_loader.rb
- move all regexps to constants in ThemeLoader
- format ThemeLoader consistently
- add helper method to resolve theme color
- fix the background color resolution mess in convert_table
- set page_bg_color to FFFFFF by default (disallow nil)
- remove dead code dealing with margins
- reomve dead create_stamps method
> resolves #195 perform code cleanups

- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- restore value of text rendering mode instance variable after PDF import
- resolves rendering problems with running header/footer content
> resolves #251 restore text rendering mode after PDF import

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- enable PDF page import using block image macro
- don't allow import_page to alter page size & layout of subsequent pages
- move to first content page before defining page stamps for running content
- add a method page_is_empty? to check if page is empty
- use page_is_empty? method to determine whether to delete last page
> resolves #177 enable PDF page import using block image macro

- lib/asciidoctor-pdf/converter.rb
- range should be calculated relative to toc_page_number
> resolves #322 correctly calculate toc page range

- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- allow theme to set alignment for headings (section titles, discrete headings and toc title)
> resolves #343 allow theme to set alignment for headings

- lib/asciidoctor-pdf/converter.rb
- fix use of invalid variable name
- autoload OpenURI before reading image
- fix duplicate forward slash in resolved path
> resolves #467 fix embedding of remote images

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/core_ext.rb
- lib/asciidoctor-pdf/core_ext/string.rb
- lib/asciidoctor-pdf/roman_numeral.rb
- implement pred method for String
- implement pred method for RomanNumeral
- call pred method instead of next if reversed option is set on list
- switch to integer value below first char or roman numeral in sequence
> resolves #491 support reversed option on ordered list

- lib/asciidoctor-pdf/converter.rb
- hex encode anchors that contain characters outside the ASCII range
- squelch the following warning: regexp match /.../n against to UTF-8 string (pdf-core < 0.6.1)
> resolves #481, #301 encode anchors containing characters outside ASCII range in hex

- lib/asciidoctor-pdf/rouge_ext/formatters/prawn.rb
- correctly calculate width of largest line number
> resolves #402 size line number gutter appropriately

- lib/asciidoctor-pdf/converter.rb
- when highlighting with Pygments, don't drop whitespace in front of conum on last line
- move line feed fragment to constant
- don't insert a forced space before conum (since we now preserve the spaces)
- disable Pygments' strip newline behavior (minor optimization only)
> resolves #470 don't drop whitespace in front of conum on final line

- lib/asciidoctor-pdf/converter.rb
align left edge of the table title to left edge of table when table is not aligned to left margin
> resolves #469 align table title to left edge of table

- lib/asciidoctor-pdf/converter.rb
- don't orpha the space between conums when extracting
- only look for conums on a line that includes < (minor optimization)
> resolves #506 don't orphan space between conums

- lib/asciidoctor-pdf/converter.rb
- create a single empty cell if table is empty
- get number of rows from rowcount attribute
> resolves #480 don't crash on empty table

- lib/asciidoctor-pdf/converter.rb
- top value with % unit positions element relative to page bounds
- top value with vh unit positions element relative to canvas
> resolves #418 add more control over position of elements on title page

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- allow font properties to be set per page side and column in running content
- update theming guide to reflect new structure of keys for running content
> resolves #454 allow font properties to be set per element in running content

- lib/asciidoctor-pdf/converter.rb
- add support for root xref (e.g., <<included-doc#>>)
- define anchor point at top of first content page
- link root xref to anchor point at top of first content page
- move logic to derive anchor from id to a helper method
- rename anchor attribute to pdf-anchor
> resolves #521 add support for root xref

- lib/asciidoctor-pdf/converter.rb
- ensure start_new_chapter always get executed at a chapter transition
- only start new page in start_new_page if cursor is not at page top
- minor code optimization
> resolves #524 ensure start_new_chapter is always called at chapter transition

- lib/asciidoctor-pdf/asciidoctor_ext/section.rb
- lib/asciidoctor-pdf/converter.rb
- add part? method to Section
- add part_or_chapter? method to Section
- call start_new_part at the start of each part
- call layout_part_title to layout part title
- comments
> resolves #329 add page break before book part

- lib/asciidoctor-pdf/converter.rb
- add support for literal and verse table cell styles
- preserve paragraph breaks in text-based table cells
- let theme control default font style for table header cell
> resolves #538 add support for literal and verse table cell styles

- data/themes/base-theme.yml
- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- display title for abstract
- allow abstract title to be customized by theme
> resolves #582 display title for abstract

- lib/asciidoctor-pdf/converter.rb
- move cursor to first non-imported content page before calculating running content dimensions
> resolves #616 fix running content dimensions

- lib/asciidoctor-pdf/converter.rb
- assign page number label to each page so page navigator stays in sync
> resolves #641 assign page number label to each page

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/index_catalog.rb
- lib/asciidoctor-pdf/sanitizer.rb
- remove repeating spaces
- remove XML tags
- decode character references
- categorize terms that start with symbols under @ category
- add escape_xml helper to Sanitizer module
> resolves #644 sanitize index terms

- docs/theming-guide.adoc
This makes it clear how to disable non facing pages for specific  parts and chapters
> Document nonfacing option for sections

- lib/asciidoctor-pdf/converter.rb
- show poster image for local video
- fetch and display thumbnail of YouTube and Vimeo video as poster if allow-uri-read is set
- show video target if poster image is not available
> resolves #287 display poster image for video with link to video file/URI

- lib/asciidoctor-pdf/rouge_ext/formatters/prawn.rb
- support underline style
- dup style set so we're working on a copy
> resolves #665 support underline style for token in Rouge theme

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb
- lib/asciidoctor-pdf/measurements.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/theme_loader.rb
- refactor measurement value helpers into module
- raise argument exception in to_pt if units are not recognized
- allow units to be passed to to_pt as symbol
> resolves #677 refactor measurement value helpers into module

- lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb
- decrement amount of placeholder characters if their width exceeds max width
I took your proposal because it felt 'more correct' and intuitive.
I removed the inline assignment since I felt it makes the code harder to read than it has to be.
> resolves #388 Duplicate inline image rendering

- lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb
- use character spacing to distribute extra space not covered by placeholder chars
- force at least one placholder char for narrow images and use negative character spacing to recover overrun
- simplify how spacer count is computed
> resolves #686 use character spacing to fine-tune width of placeholder for inline image

- lib/asciidoctor-pdf/converter.rb
- use update_colors to set color space before drawing image if color space is empty
- clarify code comments
> resolves #688 set color space when block image occurs on page by itself

- lib/asciidoctor-pdf/converter.rb
- keep block image on same page as caption
- calculate height of caption accurately using dry_run
- resize SVG to fit on page with caption if taller than content area of single page
- advance page manually instead of using keep_together to place SVG
- minor code cleanups
> resolves #690 keep block image with caption; resolves #691 resize SVG to fit page

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- make header cell in body inherit styles from the table head cells
- document default values in theming guide for table header cells
> resolves #239 make header cell in body inherit styles from table head

- lib/asciidoctor-pdf/converter.rb
- add support for image-base icons
- allow icon image to be specified explicitly
> resolves #479 add support for image-based icons

- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn-table_ext.rb
- lib/asciidoctor-pdf/prawn-table_ext/cell/text.rb
- patch text cell to remove cursor advancement
- remove hack in default theme for cell padding
> patch text cell to remove cursor advancement

- lib/asciidoctor-pdf/converter.rb
- map section-title attribute in running content to the current section if page has no section
- only search for section title within current part or chapter
> resolves #709 map section-title attribute to current section if page has no section

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- toc_title inherits from heading_h2 which inherits from heading which inherits from base
> resolves #701 allow toc title properties to be controlled by theme

- lib/asciidoctor-pdf/converter.rb
- in the case the preface is defined using a preamble block, and the
preface has a title, list it in the table of contents
> resolves #732 list preface with title in table of contents

- data/themes/base-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- add table_border_style and table_border_grid keys to theme
- document new keys
- rename border hash to border_width
- consolidate / cleanup code
> resolves #766 allow theme to set style of table border and grid

- lib/asciidoctor-pdf/converter.rb
- none simply hides the bullet (aka visibility: hidden)
- no-bullet shifts item text to (approx) left-hand margin of bullet column
- unstyled removed indentation from the list itself
- warn if list style is unrecognized
> implement none, no-bullet and unstyled unordered list styles

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
* use advance_page in keep_together instead of start_new_page
> resolves #791 fix layout error causes by nested keep together blocks

- asciidoctor-pdf.gemspec
- see https://github.com/mogest/prawn-svg/pull/94
- also resolves #741; see https://github.com/mogest/prawn-svg/issues/91
> resolves #777 upgrade prawn-svg to allow generic font names to be mapped in SVG

- lib/asciidoctor-pdf/converter.rb
- add support for the xrefstyle attribute, which allows the style of
cross reference text to be controlled
- add fallback to old behavior when using Asciidoctor < 1.5.6
> resolves #464 add support for xrefstyle attribute

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
I'm not sure if this is the right approach and there is probably a better name for the attribute but this should help get the discussion started. :smile:
> resolves #813 allow page side to be based on actual page number

- lib/asciidoctor-pdf/converter.rb
> resolves #864 add support for reftext for bibliography entry

- CHANGELOG.adoc
- WORKLOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- implement text alignment roles on outline lists
- add theme setting to control alignment of item text in outline list
- consolidate code
> resolves #182 implement text alignment roles on outline lists

- CHANGELOG.adoc
- lib/asciidoctor-pdf/converter.rb
> resolves #934 fix crash when menu macro is used in a section or block title

- CHANGELOG.adoc
- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
> resolves #105 don't add title page and show doctitle above content when doctype is article

- lib/asciidoctor-pdf/prawn-table_ext.rb
- lib/asciidoctor-pdf/prawn-table_ext/cell.rb
> resolves #990 allow table border color to be transparent

- CHANGELOG.adoc
- lib/asciidoctor-pdf/asciidoctor_ext.rb
- lib/asciidoctor-pdf/asciidoctor_ext/document.rb
- lib/asciidoctor-pdf/converter.rb
- spec/footnotes_spec.rb
- revert document state after finishing a dry run
> resolves #1047 fix duplication of footnotes in keep together regions

- CHANGELOG.adoc
- lib/asciidoctor-pdf/converter.rb
- spec/table_spec.rb
> resolves #1164 add support for default theme alignment for tables

- README.adoc
Took much longer to figure this out than I wanted, maybe a small write-up will help others.
> Add explanation for PDF import using image::[]

- CHANGELOG.adoc
- lib/asciidoctor-pdf/formatted_text/transform.rb
- spec/reference/text-formatter-inline-role-bg.pdf
- spec/text_formatter_spec.rb
> resolves #1223 allow to define text background and border on inline marks

- CHANGELOG.adoc
- lib/asciidoctor-pdf/formatted_text/transform.rb
- spec/text_formatter_spec.rb
- allowing role to override default styles for element
> resolves #1219 pass styles for inline elements downwards when parsing

- lib/asciidoctor/pdf/converter.rb
- spec/section_spec.rb
- don't reapply indent for nested sections
- indent entries in toc
- outdent discrete headings
- outdent abstract
- outdent footnotes
- don't indent index section
> resolves #1335 implement section indent properly

- docs/theming-guide.adoc
After #1326 text-decoration was added and not documented
> adds documentation about text-decoration in role category

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- lib/asciidoctor/pdf/index_catalog.rb
- spec/running_content_spec.rb
* set page_numbering_start_at theme key to an integer value
> resolves #560 allow page numbering to start after first page of body

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/running_content_spec.rb
* interpret integer value of running_content_start_at theme key as (physical) body page number
> resolves #1455 allow running content to start after first page of body

- spec/break_spec.rb
- spec/outline_spec.rb
- spec/pdf_info_spec.rb
- spec/running_content_spec.rb
- spec/xref_spec.rb
- eql does not attempt to cast type
> use eql in test suite instead of eq

- .github/workflows/ci.yml
This reverts commit 5945997882c7b3d97e1ec8b6ecb8b2f9e5b6de3b.
> Revert "disable JRuby target in GitHub Actions until action is fixed"

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/table_spec.rb
* by passing argument to fit-content function
> resolves #1494 allow caption max-width to be set to percentage of content

- lib/asciidoctor/pdf/converter.rb
compute chapter and section info for toc pages eagerly when building maps
> consolidate section info construction

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/running_content_spec.rb
when partnums attribute is set
> resolves #1610 set part-numeral attribute on running pages in part

- README.adoc
> Include reference to KDP and their need for flattened, i.e. optimized files.

- docs/theming-guide.adoc
I updated documentation with themes that are bundled with Rouge.
> Update doc with bundled Rouge styles

- .github/workflows/ci.yml
- lib/asciidoctor/pdf/optimizer.rb
* patch RGhost::GSAlone to handle command arguments properly
* install Ghostscript in CI job on Windows and enable optimizer tests on Windows
* add Chocolatey step job config to install ghostscript
> resolves #1790 fix and test optimizer on windows

- .travis.yml
Suggested-by: Dan Allen <dan.j.allen@gmail.com>
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>
> Add Prawn 2.3 to the build matrix

- spec/cli_spec.rb
- spec/hyphens_spec.rb
- spec/image_spec.rb
- spec/optimizer_spec.rb
- spec/source_spec.rb
- spec/spec_helper.rb
- use if and unless options provided by rspec to filter tests
- delegate windows? to Gem.win_platform? to get a consistent result
- add jruby? helper
- add gem_available? helper to check if gem is available (delegating to Gem.loaded_specs.key?)
- use Gem::Version to compare versions
> use rspec conditionals to filter tests instead of a postfix conditional on the test or context

- .github/workflows/ci.yml
Before: [9m2s](https://github.com/asciidoctor/asciidoctor-pdf/runs/1389540113?check_suite_focus=true#step:11:30)
After: [7m5s](https://github.com/slonopotamus/asciidoctor-pdf/runs/1389664290?check_suite_focus=true#step:11:30)
> speedup JRuby CI

- README.adoc
> Update README.adoc, just a small typo

- CHANGELOG.adoc
- Gemfile
- README.adoc
- asciidoctor-pdf.gemspec
- spec/spec_helper.rb
- spec/table_spec.rb
- a fix for https://github.com/prawnpdf/prawn-table/issues/42 is already incorporated into the code base
- remove assertion exception for prawn-table 0.2.2
- drop recommendation to use development version of prawn-table
> use prawn-table release

- CHANGELOG.adoc
- add issue numbers to enhancement for breakable by default
- minor copyedits and formatting changes
> add issue numbers to default breakable enhancement

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/list_spec.rb
- spec/paragraph_spec.rb
- spec/table_spec.rb
permitted where font properties are accepted
> resolves #2032 allow theme to control line height for blocks using line-height property

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/image_spec.rb
fix condition that assumed value was singular
> resolves #2119 allow border width of block image to be specified as an array

- CHANGELOG.adoc
- docs/modules/theme/pages/asciidoc-attributes.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/index_spec.rb
* control styles of sequential page numbers in index
* only applicable when media=screen
> resolves #1656 introduce index-pagenum-sequence-style document attribute

- README.adoc
- docs/modules/ROOT/pages/image-scaling.adoc
- docs/modules/ROOT/pages/whats-new.adoc
- fix broken links in README
- move image discussion link to docs from README
> add patch release information to What's New page

- docs/modules/theme/pages/thematic-break.adoc
The rest of this page refers to thematic break so I assume this is supposed to be thematic-break instead of sidebar?
> correct example text for padding

- docs/modules/ROOT/pages/image-scaling.adoc
As discussed here: https://asciidoctor.zulipchat.com/#narrow/stream/288690-users.2Fasciidoctor-pdf/topic/Inconsistent.20image.20size.20in.20table.20cells/near/365805999
Added clarification to image sizing and small section about inline image behavior in table cells.
> add section about inline image scaling in table cells

- CONTRIBUTING-CODE.adoc
Typo "compoent" fixed to "component".
> Update CONTRIBUTING-CODE.adoc to fix a typo
