- lib/asciidoctor-pdf/converter.rb
Let editor can use font fallbacks settings in themes.
> enable font_fallbacks support

- lib/asciidoctor-pdf/converter.rb
- retrieve the anchor name from the fragment attribute
- handle inter-document xrefs by consulting the path attribute
- honor the reftext of the destination
- warn if an xref cannot be resolved
> resolves #56 fix xref to sections

- lib/asciidoctor-pdf/converter.rb
To allow a custom page size to be used, we need to check if the
argument passed in the theme is a String, for which we ought to upcase
to use in Prawn converted, or keep the custom value to be passed over
it.
This has been tested using a custom theme with:
,----
| ...
| page:
|   ...
|   size: [508, 635]
|   ...
| ...
`----
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
> theme: Allow custom page size setting

- lib/asciidoctor-pdf/converter.rb
- support font size, family and style for cells in the table head row
- support font size and family for cells in table body rows
- normalize endlines of cell content in table head row
> resolves #139 allow theme to set font size & family of table cells

- lib/asciidoctor-pdf/converter.rb
- right align list marker in list indent for outline lists
- don't indent colists
- separate list marker from list text by ex width
- guard against orphan list marker when item starts near bottom of page
> resolves #140 position list marker correctly

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/prawn_ext/images.rb
- lib/asciidoctor-pdf/theme_loader.rb
- allow background image to be specified for all pages
- allow background image to be specified for title page
- resolve background image relative to pdf-stylesdir (theme dir)
- allow background color to be specified for title page
- add fill_absolute_bounds convenience method
> resolves #134 allow page background image to be specified

- lib/asciidoctor-pdf/converter.rb
- don't crash if sectids are disabled
- get links from TOC and outline working when sectids are disabled
> resolves #70 don't crash if sectids attribute is disabled

- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/prawn_ext/formatted_text/transform.rb
- lib/asciidoctor-pdf/theme_loader.rb
- parse CMYK color values in theme
- parse CMYK color values in formatted text
- avoid redundant processing of color values when loading theme
- mixin color types into color values
- show example of CMYK value in default theme
- code formatting
> resolves #155 support CMYK color values

- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
Adds support for the following styles on toc:
- toc_font_family
- toc_font_size
- toc_font_style
- toc_indent
- toc_dot_leader_content
- toc_line_height
- toc_h<n>_font_color
- toc_margin_top
- slightly tweak width calculation for dot leaders
> resolves #167 allow theme to control style of table of contents

- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
- add outline_list_marker_font_color setting to control marker font color
- rename toc_dot_leader color to toc_dot_leader_font_color for consistency
- use glyph for conum even when conum font color is not set
- always fallback to base font color if not set
> resolves #170 allow font color of outline list marker to be set by theme 

- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- if content to keep together exceeds a page, don't insert a page break
> resolves #183 don't insert page break before content that exceeds a page

- Gemfile
- README.adoc
- asciidoctor-pdf.gemspec
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- set Prawn version to >= 1.3.0 and < 3.0.0
- convince Bundler to install Prawn 1.3.0 if Ruby version < 2.0.0
- resolve missing on_page_create method
- add check for on_page_create method since its status is questionable
> resolves #68 upgrade Prawn

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/theme_loader.rb
- default to native image width scaled by 75% by default
- allow explicit width to be set using pdfwidth attribute
- enforce max width of 100%, except for pdfwidth or scaledwidth
- make alt text a link if image cannot be resolved and link attribute is present
- align alt text to honor image alignment
- add helper methods to convert to pt from string or number
- don't advance to new page if already at top of page
- code cleanups and optimizations
> resolves #76 allow fine-grained control over image width

- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- turns out, setting bounds directly doesn't work across pages
- instead, set padding on bounds explicitly around dry run
> resolves #215 fix dry run calculation of block height (again)

- lib/asciidoctor-pdf/converter.rb
- use the table background color, even if FFFFFF (i.e, white)
- remove logic to force table background to FFFFFF when nested inside a block
- if both the table bg color and one of the row colors is nil, then
color from the alternate row will bleed through on rowspans (prawn-table issue 45)
> resolves #214 use table background color, even if white

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/coderay_encoder.rb
- lib/asciidoctor-pdf/rouge_ext.rb
- lib/asciidoctor-pdf/rouge_ext/css_theme.rb
- lib/asciidoctor-pdf/rouge_ext/formatters/prawn.rb
- lib/asciidoctor-pdf/rouge_ext/themes/pastie.rb
- add integration with Rouge for highlighting source listings
- guard indentation within Rouge formatter
- organize the code to setup source highlighting
- enable line number support when highlighting with Rouge
- add pastie theme for Rouge
- patch Rouge style lookup (see https://github.com/jneen/rouge/issues/280)
> resolves #247 add support for the Rouge source highlighter

- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- permit the value of "middle" as an alias for "center"
- rename attribute from valign to vertical_align to be consistent w/ CSS
- update theming guide accordingly
> resolves #264 modify vertical alignment setting for running header/footer

- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- allow header_line_height & footer_line_height to be specified in theme
- properly calculate the height and placement of running content
- placement of image in running content should respect padding settings
- document header_line_height & footer_line_height in theme guide
- update default theme to use new settings
> resolves #274 make line height in running header/footer configurable

- examples/chronicles-example.adoc
- lib/asciidoctor-pdf/converter.rb
- use noheader and nofooter attributes to disable running header/footer
- allow pagenums attribute to control use of {page-number} attribute in running header/footer
- enable pagenums attribute by default
- minor cleanups
> resolves #205 enable pagenums by default

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- support use of inline image macro in value of page_background_image theme key
- allow page background to be set by document (using page-background-image attribute)
- rename title-background-image attribute to title-page-background-image
- refactor background image resolution into a method
- document background image keys in theming guide
> resolves #222 parse inline image macro value of page_background_image

- data/themes/base-theme.yml
- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
- remove use of horizontal_rhythm and vertical_rhythm from converter
- introduce block-specific padding keys
- introduce vertical_spacing key
* used as a fallback for a block's margin_bottom when key is missing
> resolves #289 remove use of "rhythm" theme keys from converter

- lib/asciidoctor-pdf/prawn_ext.rb
- lib/asciidoctor-pdf/prawn_ext/font/afm.rb
- for AFM fonts, handle conversion to windows-1252 encoding more gracefully
> resolves #290 handle conversion to windows-1252 more gracefully

- lib/asciidoctor-pdf/converter.rb
- use map for ViewerPreferences
- enable /DisplayDocTitle preference to show doctitle in window title bar
- use /OpenAction to set initial magnification
- don't use /FitWindow (it changes the window size to fit the document)
> resolves #303 use map for ViewerPreferences; set initial magnification

- README.adoc
asciidoctor, I've corrected a typographical error in the documentation of the [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf) project. You should be able to merge this pull request automatically. However, if this was intentional or you enjoy living in linguistic squalor please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.
> Fixed typographical error, changed accomodate to accommodate in README.

- asciidoctor-pdf.gemspec
Update `Prawn/Icon` from `v0.6.4` to `1.0.0`. 
The only (potentially) breaking changes involve the use of a small number of icons removed from the `octicon` font. See the  [changelog](https://github.com/jessedoyle/prawn-icon/blob/master/CHANGELOG.md).
> update prawn-icon to 1.0.0

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/theme_loader.rb
This patch allows for admonition icon customization via the pdf theme.
Here's an example of the theme syntax:
```yaml
admonition:
icon:
tip:
key: fa-arrows
color: 0099FF
size: 14
```
Supported icon keys currently are: `key`, `color` and `size`. If any of these are not specified, they will remain as the Asciidoctor defaults.
I haven't tested the patch to ensure that I haven't broken something, so it's probably best to double-check that everything works okay!
> resolves #121. Admonition icon customization by theme.

- README.adoc
Most of the icon enabling instructions is copied from issue #97. Also moved the important tip about sourcecode highlighting within the coderay section
> Add icon rendering documentation with icon sets

- data/themes/base-theme.yml
- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
Resolves #319.
Visually confirmed in Evince: File > Properties.
> Set default page size to A4

- .gitignore
- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
The feature could be re-introduced with theming support later on.
As it stands before this change, it limits the styling of abstract blocks too much.
Fixes #378.
> Remove hardcoded bold font for first line in abstract

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/theme_loader.rb
- preprocess all hex color values, regardless of key name
- update documentation to make the syntax variants more clear
> resolves #381 preprocess all hex color values

- lib/asciidoctor-pdf/converter.rb
This is the corresponding change related to asciidoctor/asciidoctor#1453.
> Add option to control generation of timestamps.

- docs/theming-guide.adoc
Note that the Gradle Link does not work until https://github.com/asciidoctor/asciidoctor-gradle-examples/pull/17 is merged.
> Add hints for how to apply styles using Maven and Gradle.

- lib/asciidoctor-pdf/formatted_text/formatter.rb
- collapse all whitespace, not just endlines, when normalizing text
> resolves #355 collapse all whitespace when normalizing

- docs/theming-guide.adoc
Pasting the "header" YML content doesn't work on the verso side. This patch to the theming guide gives the proper information.
> Fix "header" content on verso side

- lib/asciidoctor-pdf/formatted_text/transform.rb
- decode character references (e.g., &amp;) in link URIs
- update terminology for refering to character references
- minor code cleanups
> resolves #448 decode character references in link URIs

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/theme_loader.rb
- document that each heading level is assigned a font size by the base theme
- explain how to clear the default value so the font size is inherited
- don't quote null values in theme
> resolves #460 document how to inherit font size for a given heading level

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- introduce vw unit for value of pdfwidth attribute
- vw unit scales image relative to width of page
- vw unit implies left and right bounds are edge of page
> resolves #424 add support for images to span width of page

- lib/asciidoctor-pdf/converter.rb
- show URI for link if show-link-uri or media=print is set
- surround URI with square brackets instead of round brackets
- don't italicize URI
> resolves #463 show URI for link

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/formatted_text/transform.rb
- clear placeholder text for anchor so as not to confuse line wrapper
> resolves #447 clear placeholder text used for anchor

- asciidoctor-pdf.gemspec
- lib/asciidoctor-pdf/asciidoctor_ext/list.rb
- lib/asciidoctor-pdf/asciidoctor_ext/list_item.rb
- lib/asciidoctor-pdf/asciidoctor_ext/section.rb
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/core_ext/array.rb
- lib/asciidoctor-pdf/core_ext/numeric.rb
- lib/asciidoctor-pdf/core_ext/ostruct.rb
- lib/asciidoctor-pdf/core_ext/string.rb
- lib/asciidoctor-pdf/pdf_core_ext/page.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/prawn_ext/font/afm.rb
- use method_defined? instead of respond_to? to check if method is already defined
- add %r prefix to inline regexp when used as first argument to method
- undefine normalize_encoding method before redefining
- remove stray newline in error message in normalize_encoding method
- add parentheses where required
> fix Ruby warnings

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb
- lib/asciidoctor-pdf/prawn_ext/images.rb
- don't leave file descriptor for temporary image open so it can be deleted on Windows
- warn, instead of fail, if temporary image cannot be deleted
- don't call method to unlink file if temporary image is nil
> resolves #425 allow temporary image file to be deleted

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- don't report a box height larger than the maximum content height
- minor code rearranging
> resolves #361 prevent visual block from spilling to next page without content

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- allow default value for pdfwidth attribute to be specified in theme
- only allow vw units when resolving width for block image
- use ViewportWidth module to mark width with vw units
- consolidate variable names
> resolves #455 support default value for pdfwidth attribute

- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/theme_loader.rb
- add support for recto/verso margins when attribute media=prepress
- introduce page_margin_inner and page_margin_outer keys to theme
- calculate page margin for recto and verso pages automatically
- add recto/verso support to running content
- start title page, toc, and content on recto page when media=prepress and doctype=book
- add set_page_margin helper
- add page_margin helper
- add page_side helper
- add recto_page? and verso_page? helpers
- document "prepress" publishing mode in theming guide
> resolves #383 add support for recto/verso margins

- docs/theming-guide.adoc
The given description is faulty.
Let the parent's indentation be 0. Twice the parent's indentation is 0, but "2" is the expected indentation.
To quote the default theme:
```
font:
catalog:
NotoSerif:
normal: notoserif-regular-latin.ttf
```
Consider the indentation of "normal". Its parent indentation is 4. According to the description, indentation 4*2 = 8 would be required, but actually 6 is expected.
> Fix specification of indentation.

- docs/theming-guide.adoc
PR #171 introduced a name change from `toc_dot_leader_color` to `toc_dot_leader_font_color`.
This change is not reflected in the theming guide.
> Fix toc_dot_leader_font_color theming guide documentation

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- don't pass string through transform_text if transform is none
- change transform_text to return the unmodified text if the transform is none
> resolves #584 show unmodified text if text_transform is none

- Gemfile
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/sanitizer.rb
- add multibyte-aware helpers methods to transform text
- if Ruby < 2.4, load Unicode or ActiveSupport::Multibyte, in that order, if available
- add section about Text Transforms in theming guide
- document how to activate multibyte transform support for Ruby < 2.4
> resolves #363 transform text containing multibyte characters

- lib/asciidoctor-pdf/converter.rb
- use value of docdatetime attribute to set ModDate metadata
- use value of localdatetime attribute to set CreationDate metadata
> resolves #590 use value of docdatetime & localdatetime attributes in PDF info

- data/themes/base-theme.yml
- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- add admonition_label and admonition_label_<name> categories to theme
- default default settings for admonition labels in themes
- fix vertical alignment of admonition label using manual positioning
- don't process inline formatting in admonition label
- slightly reorg and cleanup code and comments
> resolves #593 allow admonition label to be controlled by theme

- data/themes/base-theme.yml
- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- add line_style (solid, double, dashed, dotted) support to stroke_vertical rule
- rename theme keys for controlling the vertical rule in an admonition block
* admonition_border_color to admonition_column_rule_color
* admonition_border_width to admonition_column_rule_width
- introduce theme key admonition_column_rule_style
- don't draw vertical rule in admonition block if color is nil or width is 0
- adjust indentation in code
> resolves #601 add more control over vertical rule in admonition block

- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- introduce the text-alignment attribute to control the default text alignment from the document
> resolves #396 introduce document attribute to control default text alignment

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
* don't leave blank page when importing PDF page
* advance to first non-imported page when creating page stamps
> resolves #614 don't leave blank page when importing PDF page

- lib/asciidoctor-pdf/converter.rb
- disable the system font scan in Prawn SVG by clearing the default font path
> disable system font scan in Prawn SVG

- lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb
- don't crash if inline image is an unsupported format
- issue a warning instead
> resolves #587 don't crash if inline image is an unsupported format

- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- do not apply font settings for toc level to dots
- calculate title and page number width in proper context
- simplify spacer
> resolves #621 use correct number of dots when font style is applied to toc level

- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- add toc_dot_leader_levels key to theme (0-based)
- default to using dot leaders for all levels
- slightly optimize how dot leaders are managed
> resolves #631 let theme control which toc levels have dot leaders

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/index_catalog.rb
resolves #386 implement converter for index
- implement converter for index
- layout index terms in two columns (with workarounds for cursor handling)
- incrementally build index in convert_inline_indexterm handler
- add anchor points at index terms to reference from index
- render index terms as content for section marked with index style (e.g., [index])
- add pdf-pagenum-offset attribute to document to track number of front matter pages
- use low-level cursor calculation in margin to workaround bug in column_box context
- rename argument to margin methods from y to n
> resolves #386 implement converter for index

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/formatted_text/inline_destination_marker.rb
- lib/asciidoctor-pdf/formatted_text/transform.rb
- use null character as dummy text, which Prawn doesn't strip
- conceal anchor fragment in callback to prevent null character from being written
> resolves #638 don't drop anchor in text that overruns page

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/formatted_text/inline_destination_marker.rb
- lib/asciidoctor-pdf/formatted_text/transform.rb
- lib/asciidoctor-pdf/index_catalog.rb
- record page number for index term when destination for anchor is written
- maintain an internal table of the index term destinations
- filter destinations that don't have a page number assigned
> resolves #639 record page number for index term when writing anchor

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/prawn_ext/images.rb
- honor pdfwidth attribute for image in running content
- only fit image to bounds if fit=contain or fit=scale-down attribute is used
- calculate image width from percentage value based on column width, not content width
- fix alignment for SVG image in running content
> resolves #625 honor pdfwidth attribute for image in running content

- README.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
- lib/asciidoctor-pdf/theme_loader.rb
- add support for absolute measurement units to value of scaledwidth attribute
- add support for pc (pica) units
- update docs to explain px to pt conversion in more detail
- make str_to_pt method resort to pt units if units aren't recognized
- comments
> resolves #674 add support for absolute measurement units to scaledwidth attribute

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb
- lib/asciidoctor-pdf/prawn-svg_ext.rb
- lib/asciidoctor-pdf/prawn-svg_ext/interface.rb
- backport resize method
- simplify calls to Prawn::Svg::Interface
- move loading and patching of prawn-svg into prawn-svg_ext
> backport resize method from prawn-svg and use it

- lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb
- correctly distribute font height so cell allocates enough room for inline image
- incorrect distribution was leading to a negative line_gap, which was making cell too small
- applies to images whose height exceeds the line height threshold
> resolves #295 calculate height of inline image correctly in table cell

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn-table_ext.rb
- lib/asciidoctor-pdf/prawn-table_ext/cell/asciidoc.rb
- use custom Cell implementation to support AsciiDoc table cells
- supports colspan, rowspan and vertical alignment
- works best if column is assigned an explicit (relative) width
- content that exceeds height of one page is clipped (general limitation of table support in Prawn)
- extra padding from last block is added to bottom of cell
- does not (yet) inherit font properties from table cell
Also resolves duplicates #315, #445 and #358.
> resolves #6 add support for AsciiDoc table cells (including nested tables)

- lib/asciidoctor-pdf/converter.rb
- resize title logo image if it exceeds boundaries to keep it on page
- specify height when embedding image to prevent redundant calculation
- don't advance page to fit image if pinned option is specified
- disable margins on block image if pinned option is specified
- simplify cursor management when embedding title logo image
> resolves #714 resize title logo image to keep on page

- README.adoc
- lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb
- resize inline image to fit within maximum content height
- if cursor is within 1% of top bounds, then try to fit in bounds
- most likely image will advance to following page as a result
> resolves #700 resize inline image to fit within content height

- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
- add stripe role to control table striping
- values are even (default), odd, all, none
- introduce keys to control striping
- table_body_background_color is "off" value; odd rows by default
- table_body_stripe_background_color is "on" value; even rows by default
> resolves #724 introduce attribute to control table striping

- lib/asciidoctor-pdf/converter.rb
- enable "start inline" option when highlighting PHP by default
- disable setting if the mixed option is set on source block
> resolves #755 enable "start inline" option when highlighting PHP

- lib/asciidoctor-pdf/converter.rb
- introduce rendered_width_of_string and rendered_width_of_char methods
- take width of char from fallback font into account if not glyph not present in font
- calculate width of conum using correct font
> resolves #651 take fallback font into account when calculating width of string

- data/themes/default-theme.yml
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
So I figured out there is already a "dry run" pass in asciidoctor-pdf, and how to use it properly - would be nice if this was documented more obviously, but I guess it's another item on the long list of TODO's? This is *definitely* stable for multi-page sidebars; verified against full Vulkan spec (and this time checked the right build...)
Happy to take code edits, I just did what seemed sane and clean at the time.
> Fixes #259 - (Properly this time!)

- lib/asciidoctor-pdf/roman_numeral.rb
Change on reverse_each because reverse_each loops in reverse order (no
intermediate array created).
> Change on reverse.each

- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/core_ext/tempfile.rb
- replace Tempfile.new with Tempfile.create
- implement Tempfile.create for Ruby < 2.1.0
> resolves #947 prevent tempfile for remote image from being deleted before it's used

- lib/asciidoctor-pdf/converter.rb
This checks the 'icontype' and uses prawn-svg to render svg icons for admonitions.
Signed-off-by: Keith Packard <keithp@keithp.com>
> resolves #828 add support for SVG admonition icons

- lib/asciidoctor-pdf/converter.rb
Not much of a Ruby guy, but we needed to modify asciidoctor-pdf to support `margin_top`, `margin_bottom`, and `line_height` to be set per heading level.  While it's entirely possible I'm missing an edge case, it seems fairly trivial/innocuous to pass the heading level into the `layout_heading` method.
Thanks for all of your work on this incredible project.
> resolves #176 - Allow margin to be set per heading level

- docs/theming-guide.adoc
Add some information about missing glyph with default font settings 
Based on the discussion in #937
> Clears thing about glyph missing in default fonts

- CHANGELOG.adoc
- asciidoctor-pdf.gemspec
resolves #886
resolves #430
- fixes spacing around image when only viewBox is specified
- also resolves #430 adds broader support for CSS
> resolves #886 upgrade prawn-svg to 0.29.1

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
Theme setup:
```
header:
startfrom: title|toc
footer:
startfrom: title|toc
```
https://github.com/asciidoctor/asciidoctor-pdf/issues/606
> resolves #606 allow running content to be added to toc and title pages

- CHANGELOG.adoc
- examples/chronicles-example.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/core_ext/string.rb
- lib/asciidoctor-pdf/formatted_text/parser.rb
- lib/asciidoctor-pdf/formatted_text/parser.treetop
- lib/asciidoctor-pdf/formatted_text/transform.rb
- lib/asciidoctor-pdf/sanitizer.rb
- parse hexadecimal character references
- skip hexadecimal character references when transforming text to uppercase
- use abbreviate form of pack for single-character translations
- add hexadecimal character reference to chronicles example
> resolves #486 add support for hexadecimal character references

- lib/asciidoctor-pdf/index_catalog.rb
Now index terms for non latin characters are treated as other, this makes impossible to use index for languages like cyrillic. Extending alpha regex to use unicode will fix it
> Add unicode support to index terms

- CHANGELOG.adoc
- README.adoc
- asciidoctor-pdf.gemspec
- data/themes/default-theme.yml
- docs/theming-guide.adoc
- examples/chronicles-example.pdf
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/prawn_ext/extensions.rb
Happy Hacktoberfest! This is a PR that I've wanted to make for some time now.
* Update `prawn-icon` to version `2.3.0`. This update upgrades
FontAwesome from version 4 to 5.
* Update the list of supported icon fonts to include the
FontAwesome categories (`solid => fas`, `brands => fab`
and `regular => far`).
* The `fa-*` prefix may still be used to generate icons,
but a deprecation warning will be printed prompting to
use the Font Awesome 5 font categories.
* Setup `fas` to be the default font family (FontAwesome
solid).
* Remove all references to the `octicon` font. It is no
longer included in `prawn/icon`.
* Update documentation and guides that are applicable to
icon styling.
* Regenerate the `examples/chronicles-example.pdf` file to
include new icons.
This should resolve …
> resolves #891 upgrade to Font Awesome 5

- CHANGELOG.adoc
- data/themes/default-theme.yml
- examples/basic-example.adoc
- examples/chronicles-example.adoc
- lib/asciidoctor-pdf/converter.rb
- place list of footnotes at end of chapter (when doctype is book) or document (when doctype is article)
- add footnotes category to theme to style footnote list
- add additional footnotes to example documents
- honor footnotes-title attribute to control title of footnote list (unset by default)
> resolves #85 place footnotes at end of chapter (book) or document (article)

- lib/asciidoctor-pdf/converter.rb
- spec/toc_spec.rb
- if article is doctype, toc is set, and title-page is not set, insert toc betwen doctitle and content
- set base font settings before doing dry run of toc to ensure size is computed accurately
- cache whether title page is enabled
- add tests
> resolves #233 insert toc between doctitle and content for article doctype by default

- CHANGELOG.adoc
- README.adoc
- lib/asciidoctor-pdf/converter.rb
- spec/converter_spec.rb
- when data-uri is set, Asciidoctor Diagram returns absolute image paths
- this allow the input and output directory to differ while still allowing Asciidoctor PDF to locate generated images
> resolves #1033 automatically set data-uri so converter can find images generated by Asciidoctor Diagram (PR #1034)

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/theme_loader.rb
- spec/fixtures/color-like-value-theme.yml
- spec/fixtures/hex-color-shorthand-theme.yml
- spec/theme_loader_spec.rb
- YAML preprocessor should only coerce values if color is last segment in key or value begins with #
- add / update tests to cover this scenario
- update theming guide to cover changes to YAML preprocessor; fix minor typos
- remove outdated warning in theming guide about this scenario
> resolves #1089 don't coerce values that are not colors to a string

- CHANGELOG.adoc
- lib/asciidoctor-pdf/converter.rb
- spec/media_spec.rb
* don't insert blank page at start of document if media=prepress and document does not have a cover
* insert blank page after cover if media=prepress
> resolves #1181 restore media=prepress behavior

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- lib/asciidoctor-pdf/theme_loader.rb
- spec/fixtures/bundled-fonts-theme.yml
- spec/font_spec.rb
- pdf-fontsdir accepts multiple directories, separated by the path separator
- font dirs are searched until the requested font is found
- allow gem fonts dir to be referenced in font catalog of theme using GEM_FONTS_DIR token
- document support for multiple font directories, including the GEM_FONTS_DIR token, in the theming guide
> resolves #80 allow multiple font dirs to be specified

- CHANGELOG.adoc
- data/themes/base-theme.yml
- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- spec/section_spec.rb
- allow theme to control min height required after section to keep on same page
- don't shift section to next page if requirement isn't met and section is empty
> resolves #1210 allow theme to control min height required after section

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor-pdf/converter.rb
- spec/font_spec.rb
- to be compatible with JAR paths
> resolves #1250 always use ; as delimiter to separate multiple font dirs

- docs/theming-guide.adoc
After #1239 new keys were added and not documented: background-color, border-color, border-offset, border-radius and border-width
> adds documentation about new keys in role category

- docs/theming-guide.adoc
Fixes the cross reference link to 'Custom Fonts' section in the preamble of the theming guide.
> fixes wrong case for 'Custom Fonts' cross reference in theming doc

- CHANGELOG.adoc
- data/themes/base-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/running_content_spec.rb
- remove logic to process `footer_<side>_content: none` key
> resolves #1320 set default footer content in base theme

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/preamble_spec.rb
- don't promote first paragraph of preamble to lead paragraph if it already has a role
- only promote first paragraph of preamble to lead paragraph (assuming it has no role)
- clean up preamble tests
> resolves #1332 don't promote first paragraph of preamble to lead paragraph if it already has a role

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/running_content_spec.rb
- handle case when page numbering and running content don't start on same page
> resolves #1334 fix value of implicit page-count attribute

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/outline_spec.rb
- spec/pdf_info_spec.rb
* show value of untitled-label attribute in outline if doctitle is not set
* don't show entry for doctitle in outline if doctitle is not set and untitled-label attribute is unset
> resolves #1348 don't duplicate first section in outline if doctitle is not set

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/spec_helper.rb
- spec/table_spec.rb
Fix https://github.com/chloerei/asciidoctor-pdf-cjk/issues/4, Also see https://github.com/asciidoctor/asciidoctor-pdf/issues/1206 for details
Require fileutils explictly to fix following errors when run command with `rake spec`
An error occurred in a `before(:suite)` hook.
Failure/Error: FileUtils.mkdir_p output_dir
NameError:
uninitialized constant FileUtils
Did you mean?  FileTest
> resolves #1359 break CJK characters in table when scripts attribute is `cjk`

- CHANGELOG.adoc
- data/themes/base-theme.yml
- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/section_spec.rb
- set separator globally using `title-separator` document attribute
- override separator per section title using `separator` block attribute
> resolves #623 partition section title (title and subtitle)

- docs/theming-guide.adoc
Hi Dan,
Happy New Year :-)
To enhance the readability of the theming guide, I simplified the description of the footnotes keys control contents.
If you believe the words "**the list**" shall be kept, just let me know and I will update the PR to modify the description:
- From "_control the style the list of footnotes_"
- To "_control the style_ **of** _the list of footnotes_"
... unless you believe the current sentence is gramatically correct (I am not a native English speaker).
> fix footnotes keys control description in theming-guide.adoc

- .travis.yml
Because it doesn't make builds faster.
----
Do not trust what this PR message says, it is just a theory. Check build timings.
> resolves #1500 disable Travis CI cache

- .travis.yml
Note: I am unable to test that release deployment still works.
Wallclock time (with 3 parallel runners) before: ~22min
Wallclock time (with 3 parallel runners) after: ~17min
Jobs are intentionally ordered in such a way that JRuby is in the beginning. It prevents situations when all other jobs have finished, but we're still waiting for JRuby.
Some further improvements could possibly be achieved by using more modern JVM (11 instead of 8) for JRuby.
> resolves #1503 improve Travis CI build times

- .gitattributes
By default ([1]), Git for Windows performs automatic LF->CRLF conversion for text files
when checks them out into working copy.
While this behavior can be desired sometimes, it leads to issues in asciidoctor-pdf:
1. Some PDF files get corrupt, for example examples/basic-example.pdf
2. JRuby doesn't properly parse inline string blocks in Ruby files when they have CRLF line endings
Given that user cannot easily disable CRLF conversion specifically for asciidoctor-pdf repo
when they do `git clone`, this commit completely disables CRLF conversion via .gitattributes.
So, files in working copy will be byte-to-byte identical no matter what platform or environment is used
to checkout asciidoctor-pdf repository.
[1]: https://github.com/git-for-windows/build-extra/blob/master/git-extra/git-extra.ins …
> Disable Git EOL autoconversion on Windows

- docs/theming-guide.adoc
The pdf-page-size example in the current docs is incorrect. This update fixes it.
> Fix bad example per issue #1518

- .github/workflows/ci.yml
See workflow runs here: https://github.com/slonopotamus/asciidoctor-pdf/actions
This PR cannot be taken as-is because it exposes several problems:
1. [jaro_winkler (rubocop dependency) crashes compiler on Ruby 2.3 + Windows](https://github.com/slonopotamus/asciidoctor-pdf/runs/398410610#step:4:163)
2. [Several tests fail to pass on Windows](https://github.com/slonopotamus/asciidoctor-pdf/runs/398467720#step:4:121). Mostly because they're trying to execute files that are not executable from Windows point of view, but there are some failures that need additional investigation.
WRT running non-executable things, I suggest using `bundle exec <gem_binary>` instead of just `<gem_binary>`, this is more cross-platform.
> Add GitHub Actions script

- .github/workflows/ci.yml
- .travis.yml
- Gemfile
- asciidoctor-pdf.gemspec
- move rubocop deps into group in Gemfile
- exclude lint group when building on Windows
- move simplecov dep to Gemfile
> enable CI for Ruby 2.3 on Windows

- asciidoctor-pdf.gemspec
Treetop 1.5 is now five years old and some distributions have been
running with treetop 1.6 without issue for some time.
> Bump treetop to 1.6

- .github/workflows/ci.yml
At present, all Actions Windows Rubies have Bundler installed.  If an update is needed, doing so with `gem update --system` is probably a better idea.
> Windows Actions CI - use $ErrorActionPreference for bundler install step

- CHANGELOG.adoc
- lib/asciidoctor/pdf/ext/prawn/extensions.rb
- spec/table_spec.rb
- sync x and width between bounds of primary and scratch document instead of only transferring left/right padding
> resolves #820 draw background and border around entire delimited block in AsciiDoc table cell

- .rubocop.yml
- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/page_spec.rb
- in additional to fullscreen, recognize all valid combinations for page mode
- OC and Attachments are not supported at this time (since Asciidoctor PDF doesn't make use of those features)
- document the pdf-page-mode attribute in the theming guide
> resolves #840 allow page mode to be configured using pdf-page-mode attribute or page_mode theme key

- asciidoctor-pdf.gemspec
concurrent-ruby is compliant with semantic versioning https://github.com/ruby-concurrency/concurrent-ruby#versioning so ~> 1.1 is enough
> relax dependency on concurrent-ruby

- .github/workflows/ci.yml
While action is available via both names, former one is deprecated.
> Handle rename of eregon/use-ruby-action to ruby/setup-ruby

- CHANGELOG.adoc
- spec/cli_spec.rb
- spec/cover_page_spec.rb
- spec/font_spec.rb
- spec/formatted_text_formatter_spec.rb
- spec/hyphens_spec.rb
- spec/image_spec.rb
- spec/page_spec.rb
- spec/spec_helper.rb
- spec/table_spec.rb
- spec/video_spec.rb
- account for the fact that pdf-core 0.8.1 truncates whole number floats
- disable hyphens and URI cache tests if gems not available
> resolves #1542 fix numeric assertions in test suite

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/cli_spec.rb
- spec/cover_page_spec.rb
- spec/font_spec.rb
- spec/formatted_text_formatter_spec.rb
- spec/hyphens_spec.rb
- spec/image_spec.rb
- spec/page_spec.rb
- spec/spec_helper.rb
- spec/table_spec.rb
- spec/video_spec.rb
- account for the fact that pdf-core 0.8.1 truncates whole number floats
- disable hyphens and URI cache tests if gems not available
- compensate for change in how character_spacing is applied in FontMetricCache#width_of after Prawn 2.2.2
> resolves #1542 fix numeric assertions in test suite (1.5.x)

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- lib/asciidoctor/pdf/ext/prawn/extensions.rb
- spec/dest_spec.rb
- spec/image_spec.rb
- spec/spec_helper.rb
- add dest for top at end of conversion
- reset page object instead of deleting reference
- add test to verify dest for top not created if document has no body pages
> resolves #1726 prevent PDF import from corrupting references in PDF

- CHANGELOG.adoc
- lib/asciidoctor/pdf/text_transformer.rb
- spec/hyphens_spec.rb
This resolves #1715 by using the `[[:word:]]` character class instead of all non-whitespace characters for tokenization.
I decided to use unit tests for this instead of integration tests, since that gave me more control over the exceptions (such that it is independent of possible changes in the language files) and made it easier to check the output. However, as I'm completely new to Ruby, the implementation may not conform to some best practices. So please let me know if there is something that can be improved.
> resolves #1715 use more specific regexp for hyphenation

- CHANGELOG.adoc
- lib/asciidoctor/pdf/theme_loader.rb
- spec/theme_loader_spec.rb
- power operator has same precedence as multiply and divide
- like other operators, must be surrounded by a space on either side
> resolves #1813 support power operator in theme

- .yardopts
- LICENSE
- README.adoc
This commit allows GitHub to properly detect project license as seen on main project page, organization repository list and other places.
Before:
After:
> convert LICENSE file to text format

- CHANGELOG.adoc
- asciidoctor-pdf.gemspec
- allows gem to be installed on Ruby 3
> upgrade to Prawn 2.4

- .editorconfig
- .rubocop.yml
- CONTRIBUTING-CODE.adoc
….in IDE (via .editorconfig), Git (via .gitattributes) and Rubocop (via .rubocop.yml) to not having false positive message when running on a OS of CRLF linebreaks.
The setting in .gitattributes was already there, so I took that as the leading configuration.
This was something I needed to figure out when developing on Windows. 
I chose to remove some words in the docs, as for me (as a Ruby newbie) first time contributions to the project weren't simple. See https://css-tricks.com/words-avoid-educational-writing/ for similar words. 
(set to "draft" while CI jobs run)
> consistent use of LF line feeds 

- lib/asciidoctor/pdf/ext/prawn/formatted_text/box.rb
- spec/font_spec.rb
by adding an escaped unicode format to the message.
> resolves #1909 improve warning about missing characters in fonts

- docs/theming-guide.adoc
Link to Rubydoc and example were not working anymore.
> Fixing links in Extending Section

- README.adoc
This README change could be backported to 1.6.
Fixes #1976
> Fix README reference to uppercase_mb

- CHANGELOG.adoc
- lib/asciidoctor/pdf/ext/pygments.rb
- lib/asciidoctor/pdf/formatted_text/parser.rb
- lib/asciidoctor/pdf/formatted_text/parser.treetop
- lib/asciidoctor/pdf/formatted_text/transform.rb
- lib/asciidoctor/pdf/sanitizer.rb
- lib/asciidoctor/pdf/theme_loader.rb
- spec/fixtures/glyph-font-test.adoc
- spec/formatted_text_formatter_spec.rb
- spec/outline_spec.rb
- spec/section_spec.rb
Issue #1990 created an extra filtering step in a process to change the case of hex characters.
Though I'm not well up to speed on Ruby, the contribution guidelines were quite clear, hence this PR :)
The commits
* make a failing test,
* adds a test for entities in hrefs (not sure about this one, **please check that this doesn't bork URI behavior**)
* update the parser to detect A-F also
`bundle exec rspec -fd spec/formatted_text_formatter_spec.rb`  reports all passing afterwards.
> resolves #1990 handle uppercase characters in character references

- CHANGELOG.adoc
- data/themes/base-theme.yml
- data/themes/default-theme.yml
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- lib/asciidoctor/pdf/ext/asciidoctor/list.rb
- lib/asciidoctor/pdf/theme_loader.rb
- spec/list_spec.rb
- spec/theme_loader_spec.rb
* remap deprecated keys if used and warn
* rename outline_list helper method on List to list_level
* add resolve_var helper method in theme loader to avoid duplicate logic
> resolves #1894 rename the outline-list category in the theme to list

- CHANGELOG.adoc
- docs/theming-guide.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/list_spec.rb
used to control font properties and item spacing of callout lists
> resolves #1722 add callout-list category to theme

- CHANGELOG.adoc
- data/themes/base-theme.yml
- docs/modules/theme/pages/table.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/table_spec.rb
retains backwards compatibility
> use sensible fallbacks for table border color and width

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- lib/asciidoctor/pdf/ext/prawn/extensions.rb
- spec/toc_spec.rb
As part of this change, ink_toc_level was rewritten to work with any block entries instead of assuming they are sections.
> resolves #2097 allow extended converter to insert or filter toc entries by overriding get_entries_for_toc method

- docs/modules/extend/examples/pdf-converter-chapter-toc.rb
- lib/asciidoctor/pdf/converter.rb
- spec/spec_helper.rb
- spec/toc_spec.rb
- don't assign toc_extent instance variable inside method
- remove workaround in chapter TOC example in docs
- test chapter TOC example in docs
- add docs_dir and doc_file helpers to test suite
> resolves #2128 make allocate_toc method reusable

- CHANGELOG.adoc
- data/themes/base-theme.yml
- lib/asciidoctor/pdf/converter.rb
- spec/admonition_spec.rb
- spec/converter_spec.rb
- spec/example_spec.rb
- spec/running_content_spec.rb
- spec/sidebar_spec.rb
* control appearance of border using border-width value
* if border-color for element is not set or nil, fall back to value of base-border-color
* don't set default value for base_border_color and base_border_width keys on theme object
* change fallback value for table border color to base-border-color
* change fallback value for thematic break stroke color to base-border-color
* don't use base-border-width as fallback width for admonition column rule
* interpret nil value in table border color array as transparent
* interpret nil value in table border width array as 0
* don't set border colors in base theme so they can be controlled using base-border-color when extending theme
* set border width on sidebar in base theme
> resolves #2134 use base-border-color as default border color

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- lib/asciidoctor/pdf/ext/prawn.rb
- lib/asciidoctor/pdf/ext/prawn/document/column_box.rb
- spec/index_spec.rb
- patch move_past_bottom method of ColumnBox to recompute bounds if page margin has changed
- fix return value of cursor method inside block for column box
- simplify checks for page available in index section
> resolves #2149 preserve columns on subsequent pages in the index section

- README.adoc
- docs/modules/ROOT/pages/autowidth-tables.adoc
- docs/modules/ROOT/pages/breakable-and-unbreakable.adoc
- docs/modules/ROOT/pages/features.adoc
- docs/modules/ROOT/pages/index-catalog.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/install.adoc
- docs/modules/ROOT/pages/interdocument-xrefs.adoc
- docs/modules/ROOT/pages/optimize-pdf.adoc
- docs/modules/ROOT/pages/whats-new.adoc
- docs/modules/extend/pages/use-cases.adoc
- docs/modules/extend/pages/use-converter.adoc
- docs/modules/theme/pages/apply-theme.adoc
- docs/modules/theme/pages/block-images.adoc
- docs/modules/theme/pages/callout.adoc
- docs/modules/theme/pages/code.adoc
- docs/modules/theme/pages/color.adoc
- docs/modules/theme/pages/custom-font.adoc
- docs/modules/theme/pages/font-support.adoc
- docs/modules/theme/pages/language.adoc
- docs/modules/theme/pages/page-numbers.adoc
- docs/modules/theme/pages/source-highlighting-theme.adoc
- docs/modules/theme/pages/table.adoc
Thanks for all the work for the Asciidoctor PDF. As the recent announcements mentioned the docs, I'd like to support this release with a review of the docs with a grammar an spell checker. 
A review of a native speaker would still be helpful, please edit/discard my suggestions as you see them fit.
I saw that the text uses both `semi-colons` and `semicolons`, I went for `semicolons` in all places.
> Docs reviewed with grammar and spell checker

- CHANGELOG.adoc
- lib/asciidoctor/pdf/ext/prawn/extensions.rb
Make a copy of the bounds, then reassign the parent and document instead of using low-level instance variable assignments on the original bounds. By using a bounds with a parent, it also preserves the width of the bounds over page boundaries, which matters when using a column box.
> use more stable approach to recreating current bounds in scratch document

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/example_spec.rb
* indent content to align with start of title
* apply bottom margin, if appropriate
* use fallback title if title is not specified
* delegate conversion of collapsible block to convert_collapsible method
> resolves #2219 fix layout of collapsible block

- CHANGELOG.adoc
- docs/modules/ROOT/pages/breakable-and-unbreakable.adoc
- docs/modules/theme/pages/heading.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/floating_title_spec.rb
- spec/section_spec.rb
* set `heading-min-height-after` to `auto`
> resolves #2268 allow orphan detection to be enabled for all section titles and discrete headings using theme

- docs/modules/theme/pages/cjk.adoc
The previous link was for `NotoSansCJKsc-VF.ttf`.
> fix(docs): update the download link of NotoSansMonoCJKsc-VF.ttf

- CHANGELOG.adoc
- bin/asciidoctor-pdf-optimize
- docs/modules/ROOT/examples/optimizer-hexapdf.rb
- docs/modules/ROOT/pages/optimize-pdf.adoc
- lib/asciidoctor/pdf/converter.rb
- lib/asciidoctor/pdf/optimizer.rb
- lib/asciidoctor/pdf/optimizer/rghost.rb
- spec/optimizer_spec.rb
* allow custom optimizer to be registered by extending Asciidoctor::PDF::Optimizer::Base and calling register_for method
* allow custom optimizer to be selected using pdf-optimizer attribute
> resolves #2330 allow PDF optimizer to be pluggable

- CHANGELOG.adoc
- asciidoctor-pdf.gemspec
- docs/modules/ROOT/pages/icons.adoc
- lib/asciidoctor/pdf/ext/prawn/extensions.rb
- spec/icon_spec.rb
Material Design Icon font set (https://materialdesignicons.com/) has just been integrated into prawn-icon. This patch allows this icon set to be used with Asciicoctor.
Thanks for the great job done with asciidoctor/asciidoctor-pdf.
> Add support for the material design icons set (mdi)

- docs/modules/theme/pages/list.adoc
What:
1. In the ulist-marker table, move the font-color row above the font-size row.
2. In the ulist-marker-<type> table, move the font-color row above the font-family row.
Why:
Keep consistency with other Theme Keys Reference tables in which keys are ordered alphabetically.
Remark:
Sorry to bother you with this perfectionist pull request ;-) Feel free to ignore it as I guess you must be quite busy developing this great product.
> Move font-color row up in the List Category Keys ulist-marker and ulist-marker<type> tables

- docs/modules/theme/pages/quote.adoc
What:
In the quote-cite table, move the font-size row below the font-kerning row.
Why:
Keep consistency with other Theme Keys Reference tables in which keys are ordered alphabetically.
Remark:
Sorry to bother you with this perfectionist pull request ;-) Feel free to ignore it as I guess you must be quite busy developing this great product.
> Move font-size row down in the quote-cite table

- docs/modules/theme/pages/table.adoc
What:
In the table-caption table "Key" column, delete the "caption-" characters string.
Why:
Keep consistency with other Theme Keys Reference tables Key columns.
Remark:
Sorry to bother you with this perfectionist pull request ;-) Feel free to ignore it as I guess you must be quite busy developing this great product.
> Delete "caption" from the table-caption Key column

- docs/modules/ROOT/pages/optimize-pdf.adoc
Fix the URL.
The Ghostscript project has changed the URL for what the distiller preset options mean of “screen, ebook, printer, and prepress”.
> Fix link in optimize-pdf.adoc for distiller preset options doc

- docs/modules/ROOT/pages/import-pdf-pages.adoc
The link defined here in the documentation points at a defunct website that apparently has been down since at least 2021.
https://web.archive.org/web/20210315000000*/https://fromplantoprototype.com/blog/2019/08/07/importing-pdf-pages-in-asciidoctor-pdf/
The original blog article provided some technical context to the reasoning behind using this feature but from what I can tell it doesn't really add much in terms of usage instructions.
> Remove broken link from import-pdf-pages documentation

- docs/modules/extend/examples/pdf-converter-article-title-with-author-and-date.rb
- docs/modules/extend/pages/use-cases.adoc
Add a use case example that makes `author`, `revdate` and `revremark` visible in document types (e.g. `article`s) without a title page, by hooking into the converter function for the document title and adding these infos in a line below it.
Workaround for #1883
See https://github.com/asciidoctor/asciidoctor-pdf/issues/1883#issuecomment-1637196810
> document how to show author etc. without title page

- spec/converter_spec.rb
ruby3.3.0dev changes the error messages on NoMethodError with the following commit / issue:
https://github.com/ruby/ruby/pull/6950
https://bugs.ruby-lang.org/issues/18285
So make NoMethodError message check on rspec testsuite compatible with this change.
Fixes #2458 .
> resolves #2458 make NoMethodError message check in tests compatible with ruby3.3.0dev

- docs/modules/extend/pages/use-cases.adoc
I think this reads more cleanly but captures the intent of the original text?
> Fix small typos in use-cases.adoc

- docs/modules/ROOT/pages/asciidoc-attributes.adoc
- docs/modules/ROOT/pages/optimize-pdf.adoc
According to this discussion, add some clarifications and some minor adjustments to the PDF attributes docs.
I've also added some missing xrefs to the attributes list. I can't really verify if the links work right since I don't know to test the Antora deployment. Sorry :/
https://asciidoctor.zulipchat.com/#narrow/stream/288690-users.2Fasciidoctor-pdf/topic/Self-contained.20adoc.2C.20including.20theme.20configuration.3F
> Add clarification about theming to attributes docs

- CHANGELOG.adoc
- lib/asciidoctor/pdf/converter.rb
- spec/list_spec.rb
- spec/spec_helper/matchers/have_message.rb
source location is used in truncation warning message
> resolves #2502 propagate source location to table cell for description in horizontal dlist

- CHANGELOG.adoc
- lib/asciidoctor/pdf/text_transformer.rb
- spec/hyphens_spec.rb
(see commit log message for details, including caveats)
(sorry about the force push, I won't do any more of those)
> resolves #2521 don't hyphenate autolink when hyphenation is enabled

- docs/modules/ROOT/pages/optimize-pdf.adoc
Remove the 'ly' adjective suffix from the word "most", which's found in the second line of the first admonition of the page.
**EDIT**: this typo is found in previous releases of `asciidoctor-pdf`, recommend fixing this with multiple PRs if necessary.
> Fix Typo in 'optimize-pdf.adoc' Page
